# Generated by Django 4.0.4 on 2022-04-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_songs_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
